
import Head from 'next/head'
import MovieCard from '@/components/MovieCard'
import { Pagination } from 'antd'
import Slider from '@/components/Slider'
import SectionCard from '@/components/SectionCard'
import { useRouter } from 'next/router'
import Navbar from '@/components/Navbar'
import { useAuth } from '@/contexts/AuthAPI'
import { useEffect } from 'react'
import {toast} from 'react-toastify'
import Footer from '@/components/Footer'
import TextAnimation from '@/components/TextAnimation'


export default function Home({popularMovies, currentPage, news ,upcomings}) {

const router = useRouter()
const {userData} = useAuth()

const sliderImgs={
  sliderImg1: popularMovies?.results[4]['poster_path'],
  sliderImg2: popularMovies?.results[3]['poster_path'],
  sliderImg3: popularMovies?.results[5]['poster_path']
}


  return (
    <>
      <Head>
        <title>Eawards App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

<Navbar/>
<TextAnimation text1={'⚫️ Eawards - a movie review rating application'} text2={'⚫️ Rate the latest movies'} text3={'⚫️ Vote for yours favourite stars'} />

{
  userData ? <div className='w-100 text-end px-2'><p className='text-dark m-auto fs-6 py-1'>Welcome {userData.diplayName ? userData.diplayName: userData.email.slice(0,userData.email.indexOf("@"))}</p></div>:<>
  </>
}


<Slider sliderImgs={sliderImgs}/>
       <h1 className='my-4'>Eawards App</h1>


<div className="normal-cards w-100">
<SectionCard title={"Movie Reviews"} link={"/movieReviews"}  data={popularMovies?.results} />
<SectionCard title={"Upcoming Releases"} link={"/upcomings"} data={upcomings?.results} />
<SectionCard title={"Movie News"} link={"/movieNews"} data={news?.articles}  />
<SectionCard title={"About Celebraty"} link={"/AboutCelebraty"} data={upcomings?.results} />
<SectionCard title={"About Cinema"} link={"/AboutCinema"} data={upcomings?.results}  />
<SectionCard title={"Recent OTT"} link={"/RecentOTT"} data={popularMovies?.results}/>
</div>

{console.log(popularMovies.results)}

<h2 className='mt-5'>Now Playing</h2>
<div className="movies w-75">

{
  popularMovies?.results.map((item,index)=>{
    if(item?.poster_path){

      return <MovieCard img={"https://image.tmdb.org/t/p/w500/"+item.poster_path} id={item.id} type={'movie'} title={item.title} description={''} key={index} />
    }
  })
}
</div>

<Pagination className='my-4 mb-8' defaultCurrent={1} current={currentPage}  total={50} onChange={(pageNumber,pageSize)=>{
router.replace(`/home/${pageNumber}`)
}}/> 


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossOrigin="anonymous"></script>
    </main>
    <Footer/>
    </>
  )
}



export const getServerSideProps = async(context)=>{
    try {
  const result = await fetch(`http://localhost:3000/api/movieApis/1`,{ cache: 'force-cache' })
  const res = await result.json()
  const popularMovies = res.response

const newsRes = await fetch(`http://localhost:3000/api/movieNews/${'bollywood'}`,{ cache: 'force-cache' })
const news = await newsRes.json()

const upcomingsRes= await fetch("http://localhost:3000/api/upcomings/1",{
  cache: 'force-cache' 
})
const upcomings = await  upcomingsRes.json()

const currentPage = 1

  return {
    props:{
  popularMovies,
currentPage, 
news,
upcomings
    }
  }
} catch (err) {
console.log(err)
    }

}